site_name: BiomolecularStructures
site_author: Simon Malischewski Henning Schumann Philipp Gerling Simon Le√ümann
repo_url: https://github.com/hng/BiomolecularStructures
theme: readthedocs
pages:
- ['index.md', 'Home']
- ['modules.md', 'Modules']
- ['kabsch.md', 'Kabsch Algorithm']
- ['pdb.md', 'PBD Utilities']

docs_dir: 'docs'
