site_name: BiomolecularStructures
site_author: Simon Malischewski Henning Schumann Philipp Gerling Simon Le√ümann
repo_url: https://github.com/hng/BiomolecularStructures
theme: readthedocs
# convention: <ModulName> - <Modul desccription>
pages:
- ['index.md', 'Home']
- ['webblast.md', 'WebBLAST - NCBI/EBI BLAST Web-API']
- ['kabsch.md', 'Kabsch - Kabsch Algorithm']
- ['mafft.md', 'MAFFT - Julia API for MAFFT commandline tool for sequence alignment']
- ['modeller.md', 'Modeller - Functions and scripts to use MODELLER with Julia']
- ['pdb.md', 'PDB - PDB Utilities']
- ['plot.md', 'MatrixPlot - Plotting Utilities']

docs_dir: 'docs'
